networks:
  wake:
  web:
    external: true

services:
  wake:
    build: .
    restart: unless-stopped
    cap_add:
      - NET_RAW
    cap_drop:
      - ALL
    network_mode: host
    environment:
      WAKE_HTTP_PORT: ${WAKE_HTTP_PORT:-}
      WAKE_MYSQL_HOST: ${WAKE_MYSQL_HOST:-}
      WAKE_MYSQL_USERNAME: ${WAKE_MYSQL_USERNAME:-}
      WAKE_MYSQL_PASSWORD: ${WAKE_MYSQL_PASSWORD:-}
      WAKE_MYSQL_DATABASE: ${WAKE_MYSQL_DATABASE:-}
      WAKE_PUBLIC_URL: ${WAKE_PUBLIC_URL:-}
      WAKE_PUSHOVER_APP_TOKEN: ${WAKE_PUSHOVER_APP_TOKEN:-}
      WAKE_PUSHOVER_USER_KEY: ${WAKE_PUSHOVER_USER_KEY:-}
      WAKE_PUSHOVER_DEVICE: ${WAKE_PUSHOVER_DEVICE:-}
